export interface Concert {
  id?: number; // Auto-generated by Dexie
  date: string; // Concert date
  location: string; // Concert location/venue
  cashAmount: number; // Amount received in cash
  bankTransferAmount: number; // Amount received by bank transfer
  totalAmount: number; // Total concert revenue
  depositCash: number; // Deposit already received in cash
  depositTransfer: number; // Deposit already received by bank transfer
  totalDeposit: number; // Total deposit received
  payments: ConcertPayment[]; // Payments to each musician
  createdAt: string; // Timestamp when record was created
  notes?: string; // Optional notes
}

export interface ConcertPayment {
  musicianName: string; // Name of the musician
  amount: number; // Amount to be paid
  paymentMethod: 'cash' | 'cachet'; // Payment method (cash or cachet/bank transfer)
  paid: boolean; // Whether the payment has been made
}

export interface BudgetSummary {
  totalRevenue: number; // Total money received from all concerts
  totalCash: number; // Total cash received
  totalBankTransfer: number; // Total bank transfers received
  totalPaidOut: number; // Total paid to musicians
  totalCashPaidOut: number; // Total paid in cash
  totalCachetPaidOut: number; // Total paid via bank transfer
  currentBalance: number; // Current balance (revenue - paid out)
  currentCashBalance: number; // Current cash balance
  currentBankBalance: number; // Current bank balance
}

export interface Expense {
  id?: number; // Auto-generated by Dexie
  date: string; // Expense date
  description: string; // What was purchased/repaired (e.g., "Speaker repair", "Drum head")
  amount: number; // Amount spent
  refundedTo: string; // Musician who will be refunded
  refunded: boolean; // Whether the refund has been made
  paymentMethod: 'cash' | 'transfer'; // How it will be refunded
  createdAt: string; // Timestamp when record was created
  notes?: string; // Optional notes
}

export interface MusicianInvoice {
  id?: number; // Auto-generated by Dexie
  musicianName: string; // Name of the musician
  date: string; // Invoice date
  description: string; // What was purchased
  amount: number; // Invoice amount
  verified: boolean; // Whether this has been verified/approved
  createdAt: string; // Timestamp when record was created
  notes?: string; // Optional notes
}

export interface MusicianBalance {
  musicianName: string;
  totalEarned: number; // Total amount earned by this musician from concerts
  totalCash: number; // Total earned in cash
  totalCachet: number; // Total earned via bank transfer
  totalPaid: number; // Total already paid
  totalExpenseRefunds: number; // Total expenses to be refunded to this musician
  totalInvoices: number; // Total invoices submitted by this musician
  invoiceDifference: number; // Difference between payroll and invoices (payroll - invoices)
  remainingToPay: number; // Amount still owed (includes concert payments and expense refunds)
}

// Transaction Log Types
export type TransactionType = 
  | 'concert_income'      // Concert revenue received
  | 'deposit_income'      // Deposit received
  | 'payment_out'         // Payment to musician
  | 'expense_out'         // Expense refund to musician
  | 'invoice_submitted';  // Invoice submitted by musician

export interface Transaction {
  id: string;                    // Unique transaction ID
  date: string;                  // Transaction date
  type: TransactionType;         // Type of transaction
  description: string;           // Human-readable description
  amount: number;                // Transaction amount
  paymentMethod?: 'cash' | 'transfer' | 'cachet'; // Payment method if applicable
  relatedMusician?: string;      // Musician involved (if applicable)
  relatedConcert?: string;       // Concert location (if applicable)
  isIncome: boolean;             // True for income, false for expense
  status: 'completed' | 'pending'; // Transaction status
  createdAt: string;             // When transaction was recorded
}

